---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-feature-build
steps:
- name: push-feature-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_BRANCH/\//-}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - feature/*
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: fAf5FwcaTb260T5gggfW0MN8sJEIhGzcX0c6SrA5CrMqY1rgaqV2dw==
---
kind: secret
name: docker_password
data: On9Zz9kKgFYinSaBOPNeQSUr9Tq3aoS/ZSV7FvDmP/3QgFQ6C2vlZ7vamAugDfeI+zG9FUyn58hXrFFG4XrS4w==
---
kind: signature
hmac: 45ec8892515b156b06d57e48b92a6082c06c2b9f4ed404a6feb5f706bde4f8d4

...
